### ISSUE TITLE
2022.5.18米游社接口被更改后无法使用米游社相关功能

### ISSUE THREAD

**Issue by CeciliaAki** [ixCiel/Adachi-BOT#8]
### 问题描述

如题。
对原先已设置cookie，能够正常使用uid查询功能和实时便笺、签到等功能的机器人使用git pull更新接口后，再使用npm run init初始化启动机器人，随后在QQ上对机器人发送“uid”查询指令和实时便笺指令反馈如下：
![(T M_9`4P_K4MK GH JR3~E](https://user-images.githubusercontent.com/103917391/169013941-65738cf7-1414-4b48-8ab7-3807134534b6.png)

### 复现流程

对5.18前已设置cookie，能够正常使用uid查询功能和实时便笺、签到等功能
但是5.18下午接口更改相关功能失效的的机器人使用**git pull**更新接口
再使用**npm run init**初始化启动机器人。

### 运行环境

```Text
npm run tool-status
```

### 当前提交

```Text
git log -1
```

### 代码状态

```Text
git status
```

**Comment by ixCiel** [comment]
是最新的么？昨天更新了几次，第一次改api的时候，改少了，第二次改多了，后来还进行了代码合并。

**Comment by CeciliaAki** [comment]
你好！我将node更新到16以后，重新部署了机器人，但是在设置cookie的时候遇到了一些麻烦。
绑定米游社通行证id后，在聊天框里设置cookie，弹出的回应是：获取游戏uid失败，请问这种问题应该怎么解决呢？
<img width="784" alt="测试" src="https://user-images.githubusercontent.com/103917391/169268134-26907f3d-664b-4d38-8585-ae63781190b6.png">

**Comment by CeciliaAki** [comment]
补充，使用uid查询功能的时候反馈如下。
![}Y1JHTA3X{{0`CL6220VKV0](https://user-images.githubusercontent.com/103917391/169271919-e6e11da3-0c1b-40f9-acfc-971f40ae15dc.png)
我想有可能是在机器人初始化配置cookie的时候出了问题，但我尝试换了很多种方法获取cookie，都没有解决问题。

**Comment by ixCiel** [comment]
看提示应该是，部署的时候，配置里面的cookie不对

**Comment by CeciliaAki** [comment]
使用的方法是火狐浏览器建立javascript:(function () { prompt("", document.cookie); })();书签获取cookie的方法，实在不知道哪里错了QAQ

**Comment by ixCiel** [comment]
> 使用的方法是火狐浏览器建立javascript:(function () { prompt("", document.cookie); })();书签获取cookie的方法，实在不知道哪里错了QAQ

看下cookie中是否有account_id和cookie_token。

**Comment by ixCiel** [comment]
不知道火狐有没有隐私模式，可以开隐私模式重新登录，获取cookie。因为有时候，虽然你看起来是登录了，但是cookie里面没有account_id和cookie_token

**Comment by CeciliaAki** [comment]
太感谢了！！！！！！！！！！ TUT
问题已解决！！
